function N2 = Function_Population(Fiber,Signal,Pump,ASE,h,c,vector)

N2 =((h*Fiber.zeta)^-1)*(vector(1,:)*Signal.Absorption/(c/Signal.Wavelength)+...
                         vector(2,:)*Pump.Absorption/(c/Pump.Wavelength)+...
                         vector(3,:)*ASE.Absorption/(c/ASE.Wavelength)+...
                         vector(4,:)*ASE.Absorption/(c/ASE.Wavelength))./...
      (1 +((h*Fiber.zeta)^-1)*...
     (vector(1,:)*(Signal.Absorption+Signal.Gain)/(c/Signal.Wavelength)+...
      vector(2,:)*(Pump.Absorption+Pump.Gain)/(c/Pump.Wavelength)+...
      vector(3,:)*(ASE.Absorption+ASE.Gain)/(c/ASE.Wavelength)+...
      vector(4,:)*(ASE.Absorption+ASE.Gain)/(c/ASE.Wavelength)));

end

